### ISSUE TITLE
Cool idea!

### ISSUE THREAD

**Issue by adamthedorsey** [adampatpattison/craft-nasaapod#1]
I'm a space nerd. I like it.

One note, I believe you mean "astronomy" and not the often confused "astrology" which relates to horoscopes and such.

https://apod.nasa.gov/apod/astropix.html

Best,
(Another) Adam

**Comment by adampatpattison** [comment]
Oh wow! I'm an idiot! 🤦‍♂️

**Comment by adamthedorsey** [comment]
All good! It's a quick fix ;)

**Comment by adampatpattison** [comment]
Found and replaced it now! Thanks for reporting.

**Comment by adamthedorsey** [comment]
Awesome!
